name: test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    steps:
      - uses: actions/checkout@v2
      - name: installation dependense
        run: |
          rsync -av ./ /root/ros2_ws/src/earthquake_info/
          cd /root/ros2_ws/src
          git clone https://github.com/HorigutiStudent/earthquake_msg.git
          sudo apt update
          sudo apt install python3-pip
          pip3 install requests
      - name: build and test
        run: |
          cd /root/ros2_ws
          bash -xv ./src/earthquake_info/test/test.bash /root 
