name: test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    steps:
      - uses: actions/checkout@v2
      - name: build and test
        run: |
          rsync -av ./ /root/ros2_ws/src/earthquake_info/
          cd /root/ros2_ws/src
          ls src/earthquake_info/test
          bash -xv ./src/earthquake_info/test/test.bash /root
